config:
  data_location: "downloaded_data"
  jenkins_username: "XYZ"
  jenkins_password: "XYZ"
  build_machine_username: "root"
  build_machine_password:
    - "password1"
    - "password2"
    - "password3"
  jenkins_base_url: "Jenkins URL"
  analysis_input_file: "build.xls"
  analysis_output_file: "report.xls"
  unsupported_path:
    - "/home"
    - "/usr"
    - "/bin"
    - "/temp"
    - "/"
  validation_type:
    - "upgrade_validation"
    - "pre_upgrade"
