jenkins_jobs:
  db_upgrade:
    - satellite6_db_upgrade_migrate
  upgrade_complete:
    - upgrade-to-6.7-rhel7
    - automation-preupgrade-6.7-scenario-tests-rhel7
    - upgrade-phase-6.7-rhel7
    - automation-postupgrade-6.7-scenario-tests-rhel7
  upgrade_sync:
    - upgrade-to-6.7-rhel7
  automation_pre-upgrade:
    - automation-preupgrade-6.7-scenario-tests-rhel7
  satellite_and_capsule_upgrade:
    - upgrade-phase--6.7-rhel7
  automation_post_upgrade:
    - automation-postupgrade-6.7-scenario-tests-rhel7